/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Stream metadata. All fields are optional strings. */
export interface JsStreamInfo {
  mimetype?: string
  extension?: string
  charset?: string
  filename?: string
  localPath?: string
  url?: string
  imageDir?: string
}
export interface JsConversionResult {
  markdown: string
  title?: string
}
/** Returns the builtin converter names in registry order. */
export declare function converterNames(): Array<string>
/** Check whether a named converter accepts the given stream info. */
export declare function converterAccepts(name: string, info: JsStreamInfo): boolean
/** Convert using a specific named converter. */
export declare function converterConvert(name: string, input: Buffer, info: JsStreamInfo): Promise<unknown>
/**
 * Convert a URL using a specific named converter's URL hook.
 * Resolves to null if the converter has no convert_url hook.
 */
export declare function converterConvertUrl(name: string, url: string): Promise<unknown>
export type JsMarkit = Markit
export declare class Markit {
  constructor()
  /** Convert a buffer to markdown. */
  convert(input: Buffer, info?: JsStreamInfo | undefined | null): Promise<unknown>
  /** Convert a local file to markdown. */
  convertFile(path: string, extra?: JsStreamInfo | undefined | null): Promise<unknown>
  /** Convert a URL to markdown. */
  convertUrl(url: string): Promise<unknown>
}
