[package]
name = "markit"
version = "0.5.3"
edition = "2021"
description = "Convert anything to markdown."
license = "MIT"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
regex = "1.13.1"
roxmltree = "0.21.1"
scraper = "0.27.0"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
zip = "8.6.0"

[[bin]]
name = "markit"
path = "src/main.rs"
